version: "3"

services:
  php:
    container_name: php
    image: phpcomxdebug
    volumes:
      - "./html:/var/www/html:delegated"
    restart: on-failure
    ports:
     - 35500:35500
    expose: 
     - "9000"

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:delegated"
    ports:
      - mode: ingress
        target: 80
        published: 80
        protocol: tcp
    restart: on-failure
  
  db_local:
    platform: linux/x86_64
    container_name: db_local
    image: mysql:8
    restart: on-failure
    command: [--innodb-flush-method=fsync]
    environment:
      MYSQL_DATABASE: "movies_reviews"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_PASSWORD: "dsi"
      MYSQL_USER: "dsiarena"
    security_opt:
      - seccomp:unconfined
    ports:
      - '3306:3306'
    volumes:
      - ./mysqldata/1:/var/lib/mysql
      - ./my.conf:/etc/mysql/conf.d/mysql.cnf
