version: "3"

services:
  php:
    container_name: php
    image: phpcomxdebug
    volumes:
      - "./html:/var/www/html:delegated"
    restart: on-failure
    ports:
     - 35500:35500
    expose: 
     - "9000"
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:delegated"
    ports:
      - mode: ingress
        target: 80
        published: 80
        protocol: tcp
    restart: on-failure